blank_issues_enabled: false
contact_links:
  - name: Vision Website
    url: https://vision.saturdaynightdead.xyz/
    about: Just in case you need to get a reference from Vision's website.
  - name: Contact the Vision Devs
    url: https://hypel.ink/VisionDevs
    about: If it's necessary, go here to contact any of the developers of Vision (via Reddit)!
